version: '2'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - ecommerce
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/ecommerce?serverTimezone=UTC
      spring.datasource.username: root
      spring.datasource.password: root
      spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect
      spring.sql.init.mode: always
      spring.jpa.hibernate.ddl-auto: create
      server.port: 8090
    networks:
      - ecommerce

  ecommerce:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    hostname: ecommerce
    networks:
      - ecommerce

networks:
  ecommerce:
    driver: bridge
